In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
parent = os.path.dirname(os.getcwd())

In [13]:

couverture_habitant_chemin = os.path.join(parent, 'data\output\couverture_habitant.csv')
couverture_habitant_chemin_final = couverture_habitant_chemin.replace("\\", "/")

# Chargement 
df_hab = pd.read_csv(couverture_habitant_chemin_final, dtype={'code_dep': str})

# en-tête
print("En-tête du DataFrame :")
print(df_hab.head())

# Infos structurelles
print(f"Dimensions : {df_hab.shape}")
print(df_hab.info())

# Descriptif statistique
print("\nStatistiques descriptives :")
print(df_hab.describe())

# Analyse statistique de la densité
print("\nStatistiques sur la densité (sites pour 10k hab) :")
print(df_hab['sites_pour_10k_hab'].describe())

# Qualité des données
print("\nValeurs manquantes :")
print(df_hab.isnull().sum())
print(f"Doublons détectés : {df_hab.duplicated().sum()}")

# Aperçu des valeurs extrêmes
print("\nTop 5 des départements les plus denses :")
display(df_hab.sort_values('sites_pour_10k_hab', ascending=False).head(5))

En-tête du DataFrame :
  code_dep  nb_sites  pop_totale  sites_pour_10k_hab
0       23       230      369015                6.23
1       48       198      347434                5.70
2       70       462      929839                4.97
3       55       420      986912                4.26
4       09       250      647507                3.86
Dimensions : (96, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   code_dep            96 non-null     object
 1   nb_sites            96 non-null     int64
 2   pop_totale          96 non-null     int64
 3   sites_pour_10k_hab  96 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 3.1+ KB
None

Statistiques descriptives :
          nb_sites    pop_totale  sites_pour_10k_hab
count    96.000000  9.600000e+01           96.000000
mean    785.614583  2.472232e+07            1.309896
std     458.702618  4.564069e+07            1.275256
min     144.000000  3.474340e+05            0.060000
25%     436.750000  2.665478e+06            0.387500
50%     718.000000  7.257458e+06            0.955000
75%     957.750000  2.280356e+07            1.677500
max    2443.000000  2.632830e+08            6.230000

Statistiques sur la densité (sites pour 10k hab) :
count    96.000000
mean      1.309896
std       1.275256
min       0.060000
25%       0.387500
50%       0.955000
75%       1.677500
max       6.230000
Name: sites_pour_10k_hab, dtype: float64

Valeurs manquantes :
code_dep              0
nb_sites              0
pop_totale            0
sites_pour_10k_hab    0
dtype: int64
Doublons détectés : 0

Top 5 des départements les plus denses :

  code_dep  nb_sites  pop_totale  sites_pour_10k_hab
0       23       230      369015                6.23
1       48       198      347434                5.70
2       70       462      929839                4.97
3       55       420      986912                4.26
4       09       250      647507                3.86

In [14]:
indice_concurrence_hhi_chemin = os.path.join(parent, 'data\output\indice_concurrence_hhi.csv')
indice_concurrence_hhi_chemin_final = indice_concurrence_hhi_chemin.replace("\\", "/")

# Chargement
df_hhi = pd.read_csv(indice_concurrence_hhi_chemin_final, dtype={'code_dep': str})

# en-tête
print("En-tête du DataFrame :")
print(df_hab.head())

# Infos structurelles
print(f"Dimensions : {df_hhi.shape}")
print(df_hhi.info())

# Descriptif statistique
print("\nStatistiques descriptives :")
print(df_hhi.describe())

# Qualité des données
print("\nValeurs manquantes :")
print(df_hhi.isnull().sum())
print(f"Doublons détectés : {df_hhi.duplicated().sum()}")

# Vérification de la plage de l'indice
hhi_min = df_hhi['hhi_index'].min()
hhi_max = df_hhi['hhi_index'].max()
print(f"Plage de l'indice HHI : [{hhi_min:.4f} - {hhi_max:.4f}]")

# Identification des marchés les plus concentrés
print("\nLes 5 départements où la concurrence est la moins forte (HHI élevé) :")
display(df_hhi.nlargest(5, 'hhi_index'))

# Vérification des anomalies
if hhi_min < 0.25:
    print(" Attention : Des valeurs HHI sont inférieures au seuil théorique de 0.25.")

En-tête du DataFrame :
  code_dep  nb_sites  pop_totale  sites_pour_10k_hab
0       23       230      369015                6.23
1       48       198      347434                5.70
2       70       462      929839                4.97
3       55       420      986912                4.26
4       09       250      647507                3.86
Dimensions : (96, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   code_dep   96 non-null     object
 1   hhi_index  96 non-null     float64
dtypes: float64(1), object(1)
memory usage: 1.6+ KB
None

Statistiques descriptives :
       hhi_index
count  96.000000
mean    0.254403
std     0.003798
min     0.250116
25%     0.251350
50%     0.253631
75%     0.255829
max     0.267514

Valeurs manquantes :
code_dep     0
hhi_index    0
dtype: int64
Doublons détectés : 0
Plage de l'indice HHI : [0.2501 - 0.2675]

Les 5 départements où la concurrence est la moins forte (HHI élevé) :

  code_dep  hhi_index
0       75   0.267514
1       06   0.265478
2       2A   0.264172
3       31   0.264055
4       59   0.263823

In [15]:
infra_stats_chemin = os.path.join(parent, 'data\output\infra_stats.csv')
infra_stats_chemin_final = infra_stats_chemin.replace("\\", "/")

# Chargement
df_infra = pd.read_csv(infra_stats_chemin_final)

# en-tête
print("En-tête du DataFrame :")
print(df_infra.head())

# Infos structurelles
print(f"Dimensions : {df_infra.shape}")
print(df_infra.info())

# Descriptif statistique
print("\nStatistiques descriptives :")
print(df_infra.describe())

# Qualité des données
print("\nValeurs manquantes :")
print(df_infra.isnull().sum())
print(f"Doublons détectés : {df_infra.duplicated().sum()}")

# Vérification de cohérence (Total 4G ne peut pas être > Total Sites)
mask_error = df_infra['total_4g'] > df_infra['total_sites']
if mask_error.any():
    print("Erreur logique détectée : Des opérateurs ont plus de sites 4G que de sites totaux.")
else:
    print("Cohérence logique vérifiée (4G <= Total).")

# Calcul de la contribution relative
df_infra['poids_reseau_pct'] = (df_infra['total_sites'] / df_infra['total_sites'].sum()) * 100
print("\nPoids de chaque opérateur dans l'infrastructure nationale :")
display(df_infra[['nom_op', 'total_sites', 'poids_reseau_pct', 'taux_4g_pct']])

En-tête du DataFrame :
             nom_op  total_sites  total_4g  taux_4g_pct
0            Orange        25215     22656        89.85
1               SFR        22256     19747        88.73
2  Bouygues Telecom        21032     19185        91.22
3       Free Mobile        17918     16605        92.67
Dimensions : (4, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nom_op       4 non-null      object
 1   total_sites  4 non-null      int64
 2   total_4g     4 non-null      int64
 3   taux_4g_pct  4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 260.0+ bytes
None

Statistiques descriptives :
        total_sites      total_4g  taux_4g_pct
count      4.000000      4.000000     4.000000
mean   21605.250000  19548.250000    90.617500
std     3020.937975   2482.759402     1.705625
min    17918.000000  16605.000000    88.730000
25%    20253.500000  18540.000000    89.570000
50%    21644.000000  19466.000000    90.535000
75%    22995.750000  20474.250000    91.582500
max    25215.000000  22656.000000    92.670000

Valeurs manquantes :
nom_op         0
total_sites    0
total_4g       0
taux_4g_pct    0
dtype: int64
Doublons détectés : 0
Cohérence logique vérifiée (4G <= Total).

Poids de chaque opérateur dans l'infrastructure nationale :

             nom_op  total_sites  poids_reseau_pct  taux_4g_pct
0            Orange        25215         29.176936        89.85
1               SFR        22256         25.753000        88.73
2  Bouygues Telecom        21032         24.336677        91.22
3       Free Mobile        17918         20.733387        92.67

In [17]:
matrice_concurrence_chemin = os.path.join(parent, 'data\output\matrice_concurrence.csv')
matrice_concurrence_chemin_final = matrice_concurrence_chemin.replace("\\", "/")

# Chargement
df_matrice = pd.read_csv(matrice_concurrence_chemin_final)

# en-tête
print("En-tête du DataFrame :")
print(df_matrice.head())

# Infos structurelles
print(f"Dimensions : {df_matrice.shape}")

# Qualité des données
print("\nValeurs manquantes :")
print(df_matrice.isnull().sum())
print(f"Doublons détectés : {df_matrice.duplicated().sum()}")

# Descriptif statistique
print("\nStatistiques descriptives :")
print(df_matrice.describe())

# Détection des doublons de nommage de régions
n_reg_raw = df_matrice['nom_reg'].nunique()
print(f"Nombre de noms de régions uniques avant nettoyage : {n_reg_raw}")

# Affichage des noms pour identifier les corrections nécessaires
print("\nListe des noms de régions bruts :")
print(df_matrice['nom_reg'].unique())

# Vérification de la complétude (présence de 0 ou de valeurs nulles)
print("\nNombre de valeurs à zéro par opérateur :")
print((df_matrice[['Bouygues Telecom', 'Free Mobile', 'Orange', 'SFR']] == 0).sum())

# Aperçu global
print("\nAperçu global du DataFrame :") 
display(df_matrice.head())

En-tête du DataFrame :
                   nom_reg  Bouygues Telecom  Free Mobile  Orange   SFR
0     AUVERGNE RHONE ALPES                 0            0    3236    21
1     AUVERGNE-RHONE-ALPES              2893         2529       0  3002
2  BOURGOGNE FRANCHE COMTE                 0            0    1625     0
3  BOURGOGNE FRANCHE COMT�                 0            0      27    32
4  BOURGOGNE-FRANCHE-COMTE              1494         1439       0  1463
Dimensions : (24, 5)

Valeurs manquantes :
nom_reg             0
Bouygues Telecom    0
Free Mobile         0
Orange              0
SFR                 0
dtype: int64
Doublons détectés : 0

Statistiques descriptives :
       Bouygues Telecom  Free Mobile       Orange          SFR
count         24.000000    24.000000    24.000000    24.000000
mean         876.333333   746.583333  1050.625000   927.333333
std         1000.424200   847.034259  1182.746649  1062.932517
min            0.000000     0.000000     0.000000     0.000000
25%            0.000000     0.000000     0.000000    12.000000
50%          571.000000   462.500000   662.500000   575.500000
75%         1595.250000  1418.750000  2071.500000  1691.750000
max         2893.000000  2529.000000  3236.000000  3053.000000
Nombre de noms de régions uniques avant nettoyage : 24

Liste des noms de régions bruts :
['AUVERGNE RHONE ALPES' 'AUVERGNE-RHONE-ALPES' 'BOURGOGNE FRANCHE COMTE'
 'BOURGOGNE FRANCHE COMT�' 'BOURGOGNE-FRANCHE-COMTE' 'BRETAGNE'
 'CENTRE VAL DE LOIRE' 'CENTRE-VAL DE LOIRE' 'CORSE' 'GRAND EST'
 'HAUTS DE FRANCE' 'HAUTS-DE-FRANCE' 'ILE DE FRANCE' 'ILE-DE-FRANCE'
 'NORMANDIE' 'NOUVELLE AQUITAINE' 'NOUVELLE-AQUITAINE' 'Normandie'
 'OCCITANIE' 'Occitanie' 'PAYS DE LA LOIRE' 'PROVENCE ALPES COTE D AZUR'
 "PROVENCE ALPES COTE D'AZUR" "PROVENCE-ALPES-COTE D'AZUR"]

Nombre de valeurs à zéro par opérateur :
Bouygues Telecom    11
Free Mobile         11
Orange               7
SFR                  3
dtype: int64

Aperçu global du DataFrame :

                   nom_reg  Bouygues Telecom  Free Mobile  Orange   SFR
0     AUVERGNE RHONE ALPES                 0            0    3236    21
1     AUVERGNE-RHONE-ALPES              2893         2529       0  3002
2  BOURGOGNE FRANCHE COMTE                 0            0    1625     0
3  BOURGOGNE FRANCHE COMT�                 0            0      27    32
4  BOURGOGNE-FRANCHE-COMTE              1494         1439       0  1463